src/viralhostrange/viralhostrange/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from viralhostrange import settings
from viralhostrangedb import views

urlpatterns = [
    path('', include('basetheme_bootstrap.urls')),
    path('', include('viralhostrangedb.urls')),
    path('api/', include('viralhostrangedb.urls_api')),
    # path('api/', include('webapi.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
]

if not settings.DEBUG:
    urlpatterns.append(
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    )
urlpatterns.append(
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
)

src/viralhostrange/viralhostrangedb/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from viralhostrangedb import views

data_source_wizard = views.DataSourceWizard.as_view(url_name='viralhostrangedb:data-source-create-step')

app_name = 'viralhostrangedb'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^import/data-source/$', views.file_import, name='file-import-view'),
    # url(r'^data_source/(?P<pk>\d+)/edit/$', views.file_import, name='data-source-edit'),
    url(
        r'^data-source/pending-mapping/$',
        views.DataSourceMappingPendingListView.as_view(),
        name='data-source-pending-mapping-list',
    ),
    url(r'^explore/$', views.browse, name='browse'),
    url(r'^explore/css/(?P<slug>[^/]*)$', views.custom_css, name='custom_css'),
    url(r'^download/$', views.download_responses, name='download_responses'),
    url(r'^data-source/$', views.DataSourceListView.as_view(), name='data-source-list'),
    url(r'^data-source/(?P<pk>\d+)/download/$', views.data_source_download, name='data-source-download'),
    url(r'^data-source/(?P<pk>\d+)/update/$', views.data_source_data_update, name='data-source-data-update'),
    url(r'^data-source/(?P<pk>\d+)/edit/$', views.DataSourceUpdateView.as_view(), name='data-source-update'),
    url(r'^data-source/(?P<pk>\d+)/virus/update/$', views.data_source_virus_update, name='data-source-virus-update'),
    url(r'^data-source/(?P<pk>\d+)/host/update/$', views.data_source_host_update, name='data-source-host-update'),
    url(r'^data-source/(?P<pk>\d+)/virus/delete/$', views.data_source_virus_delete, name='data-source-virus-delete'),
    url(r'^data-source/(?P<pk>\d+)/host/delete/$', views.data_source_host_delete, name='data-source-host-delete'),
    url(r'^data-source/(?P<pk>\d+)/delete/$', views.DataSourceDeleteView.as_view(), name='data-source-delete'),
    url(r'^data-source/(?P<pk>\d+)/$', views.DataSourceDetailView.as_view(), name='data-source-detail'),
    url(r'^data-source/(?P<pk>\d+)/explore/$', views.SelectDataFromDataSourceView.as_view(), name='data-source-browse'),
    url(r'^data-source/(?P<pk>\d+)/explore_by_virus_and_host/$', views.SelectVirusAndHostFromDataSourceView.as_view(),
        name='data-source-browse-by-virus-and-host'),
    url(r'^data-source/(?P<pk>\d+)/mapping/edit-as-label/$', views.data_source_mapping_edit,
        name='data-source-mapping-label-edit'),
    url(r'^data-source/(?P<pk>\d+)/mapping/edit/$', views.data_source_mapping_range_edit,
        name='data-source-mapping-edit'),
    url(r'^data-source-contribution/(?P<step>.+)/$', data_source_wizard, name='data-source-create-step'),
    url(r'^data-source-contribution/$', data_source_wizard, name='data-source-create'),
    url(r'^data-source/(?P<pk>\d+)/contact/$', views.contact_data_source_owner, name='data-source-contact'),

    url(r'^virus/$', views.VirusListView.as_view(), name='virus-list'),
    url(r'^virus/(?P<pk>\d+)/$', views.VirusDetailView.as_view(), name='virus-detail'),
    url(r'^virus/(?P<pk>\d+)/download/$', views.virus_download, name='virus-download'),

    url(r'^host/$', views.HostListView.as_view(), name='host-list'),
    url(r'^host/(?P<pk>\d+)/$', views.HostDetailView.as_view(), name='host-detail'),
    url(r'^host/(?P<pk>\d+)/download/$', views.host_download, name='host-download'),

    url(r'^response/ds-(?P<ds_pk>\d+)-virus-(?P<virus_pk>\d+)-host-(?P<host_pk>\d+)/update/$',
        views.response_update, name='response-update'),
    url(r'^search/$', views.search, name='search'),

    url(r'^probe_alive/$', views.is_alive, name='probe_alive'),
    url(r'^probe_ready/$', views.is_ready, name='probe_ready'),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

]

src/viralhostrange/viralhostrangedb/models.py
import colorsys
import re

from basetheme_bootstrap import user_preferences
from colorfield.fields import ColorField
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.validators import MaxLengthValidator
from django.db import models
# Create your models here.
from django.db.models import Exists, OuterRef, Q
from django.db.models.functions import Upper
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _, ugettext


class GlobalViralHostResponseValue(models.Model):
    class Meta:
        verbose_name = _("Global Viral-Host response values")
        verbose_name_plural = _("Global Viral-Host response values")

        index_together = [
            ["id", "name"],
            ["id", "value"],
            ["id", "name", "value"],
        ]

        permissions = (
            ("change_globalviralhostresponsevalue_color", "Can change Global Viral-Host response color"),
        )

    name = models.CharField(
        verbose_name=_("response__name__verbose_name"),
        help_text=_("response__name__help_text"),
        max_length=32,
        validators=[MaxLengthValidator(32)] if settings.DEBUG else [],
        unique=True,
    )
    description = models.TextField(
        verbose_name=_("response__description__verbose_name"),
        help_text=_("response__description__help_text"),
        blank=True,
        default="",
    )
    value = models.FloatField(
        verbose_name=_("response__value__verbose_name"),
        help_text=_("response__value__help_text"),
        default=-1000000,
    )
    color = ColorField(
        verbose_name=_("response__color__verbose_name"),
        help_text=_("response__color__help_text"),
    )

    def __str__(self):
        return "%s (value=%s)" % (self.name, '{0:g}'.format(self.value))

    def to_hsv(self):
        h, s, v = colorsys.rgb_to_hsv(
            int("0x" + self.color[1:3], 0) / 255,
            int("0x" + self.color[3:5], 0) / 255,
            int("0x" + self.color[5:7], 0) / 255,
        )
        return h * 360, s * 100, v * 50

    @classmethod
    def get_hsv_color_for(cls, value):
        lower = cls.objects_mappable().filter(value__lte=value).order_by("-value").first()
        upper = cls.objects_mappable().filter(value__gte=value).order_by("value").first()
        lower_hsv = lower.to_hsv()
        upper_hsv = upper.to_hsv()
        if lower.value == upper.value:
            percentage = 0
        else:
            percentage = (value - lower.value) / (upper.value - lower.value)

        hue = lower_hsv[0] * percentage + upper_hsv[0] * (1 - percentage)
        sat = lower_hsv[1] * percentage + upper_hsv[1] * (1 - percentage)
        lgt = lower_hsv[2] * percentage + upper_hsv[2] * (1 - percentage)
        return hue, sat, lgt

    @classmethod
    def get_rgb_color_for(cls, value):
        hue, sat, lgt = cls.get_hsv_color_for(value=value)
        r, g, b = colorsys.hsv_to_rgb(hue / 360, sat / 100, lgt / 50)
        return int(r * 255), int(g * 255), int(b * 255)

    @classmethod
    def get_html_color_for(cls, value):
        r, g, b = cls.get_rgb_color_for(value)
        return '#%02x%02x%02x' % (r, g, b)

    @staticmethod
    def get_not_mapped_yet_keyword():
        return 'NOT MAPPED YET'

    @staticmethod
    def get_not_mapped_yet():
        return GlobalViralHostResponseValue.objects.get(
            name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword())

    @staticmethod
    def get_not_mapped_yet_pk():
        return GlobalViralHostResponseValue.objects.filter(
            name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword()).values_list('pk', flat=True)[0]

    @classmethod
    def objects_mappable(cls):
        return cls.objects.filter(~Q(name=cls.get_not_mapped_yet_keyword()))


class DataSourceWithPendingManager(models.Manager):
    def get_queryset(self):
        pending = super().get_queryset().filter(
            responseindatasource__response=GlobalViralHostResponseValue.get_not_mapped_yet()
        ).filter(pk=OuterRef('pk'))
        return super().get_queryset().annotate(
            mapping_done=~Exists(pending)
        )


class DataSource(models.Model):
    class Meta:
        verbose_name = _("Data Source")
        verbose_name_plural = _("Data Sources")
        ordering = [Upper('name'), ]

    objects_annotated_with_pending = DataSourceWithPendingManager()

    objects = models.Manager()

    owner = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.PROTECT,
    )
    public = models.BooleanField(
        verbose_name=_("public__verbose_name"),
        help_text=_("public__help_text"),
        default=False,
    )
    name = models.CharField(
        verbose_name=_("data_source__name__verbose_name"),
        help_text=_("data_source__name__help_text"),
        max_length=128,
        validators=[MaxLengthValidator(128)] if settings.DEBUG else []
    )
    description = models.TextField(
        verbose_name=_("data_source__description__verbose_name"),
        help_text=_("data_source__description__help_text"),
        blank=True,
        default="",
    )
    raw_name = models.TextField(
        verbose_name=_("raw_name__verbose_name"),
        help_text=_("raw_name__help_text"),
    )
    kind = models.CharField(
        verbose_name=_("kind__verbose_name"),
        help_text=_("kind__help_text"),
        max_length=4,
        choices=(
            ("FILE", _("From a file")),
            ("URL", _("From an URL")),
            # ("LIVE", _("Live input")),
        )
    )
    allowed_users = models.ManyToManyField(
        to=get_user_model(),
        verbose_name=_("allowed_users__verbose_name"),
        help_text=_("allowed_users__help_text"),
        related_name='datasource_readable_set',
        blank=True,
    )
    experiment_date = models.DateField(
        verbose_name=_("experiment_date__verbose_name"),
        help_text=_("experiment_date__help_text"),
        blank=True,
        null=True,
    )
    creation_date = models.DateTimeField(
        verbose_name=_("creation_date__verbose_name"),
        help_text=_("creation_date__help_text"),
    )
    last_edition_date = models.DateTimeField(
        verbose_name=_("last_edition_date__verbose_name"),
        help_text=_("last_edition_date__help_text"),
    )
    publication_url = models.URLField(
        verbose_name=_("publication_url__verbose_name"),
        help_text=_("publication_url__help_text"),
        null=True,
        blank=True,
    )
    life_domain = models.CharField(
        choices=(
            ("archaea", _("Archaea")),
            ("bacteria", _("Bacteria")),
            ("eukaryote", _("Eukaryote")),
        ),
        verbose_name=_("life_domain.label"),
        help_text=_("life_domain.help_text"),
        null=False,
        blank=False,
        default="bacteria",
        max_length=32,
    )

    def __str__(self):
        return "%s (created on %s)" % (
            self.name,
            "???" if self.creation_date is None else self.creation_date.strftime('%Y-%m-%d %H:%M:%S %Z'),
        )

    def get_absolute_url(self):
        return reverse("viralhostrangedb:data-source-detail", args=[self.pk])

    def get_ordered_mapping(self, only_pk=False):
        return self.get_mapping(ordered=True)

    def get_mapping(self, only_pk=False, ordered=False):
        if not only_pk:
            used_responses = dict()
            for r in GlobalViralHostResponseValue.objects.filter(
                    pk__in=self.responseindatasource.values_list('response__pk').distinct()):
                used_responses[r.pk] = r
        q = self.responseindatasource.values_list('raw_response', 'response__pk')
        if ordered:
            q = q.order_by("raw_response")
        for raw_response, response_mapped in q.distinct():
            yield raw_response, response_mapped if only_pk else used_responses[response_mapped]

    @property
    def is_mapping_done(self):
        return not ViralHostResponseValueInDataSource.objects \
            .filter(data_source__pk=self.pk, response__name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword()) \
            .exists()

    @property
    def is_mapping_absent(self):
        return not GlobalViralHostResponseValue.objects \
            .filter(responseindatasource__data_source__pk=self.pk) \
            .filter(~Q(name=GlobalViralHostResponseValue.get_not_mapped_yet_keyword())) \
            .exists()

    @classmethod
    def get_not_mapped_data_sources(cls, *, owner):
        return cls.objects.filter(pk__in=cls.get_not_mapped_data_sources_pk(owner=owner))

    @classmethod
    def get_not_mapped_data_sources_pk(cls, *, owner):
        return cls._get_not_mapped_data_sources(owner=owner).distinct()

    @classmethod
    def has_not_mapped_data_sources(cls, *, owner):
        return cls._get_not_mapped_data_sources(owner=owner).exists()

    @classmethod
    def _get_not_mapped_data_sources(cls, *, owner):
        return GlobalViralHostResponseValue.get_not_mapped_yet() \
            .responseindatasource \
            .values_list("data_source__pk", flat=True) \
            .filter(data_source__owner__pk=owner.pk)

    @property
    def raw_filename(self):
        if self.raw_name is None or len(str(self.raw_name).strip()) == 0:
            raw_name = self.name
        else:
            raw_name = self.raw_name
        raw_name = str(raw_name)
        if len(raw_name) > 0 and raw_name[-1] == '/':
            raw_name = raw_name[:-1]
        try:
            raw_name = raw_name[raw_name.rindex("/") + 1:]
        except ValueError:
            pass
        raw_name = re.sub(r'([^.a-zA-Z0-9])', '_', raw_name)
        raw_name = re.sub(r'(_[_]+)', '_', raw_name)
        return raw_name

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.creation_date = timezone.now()

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/datasource_detail.html
{% extends "viralhostrangedb/base.html" %}
{%load sstatic%}
{%load i18n%}
{%load viralhostrange_tags%}

{% block title %}{{object|class_verbose_name}}{% endblock %}
{% block page_title %}
{{object|class_verbose_name}}
{% if has_responses%}
<a href="{% url 'viralhostrangedb:data-source-browse' pk=object.pk%}" role="button"
   class="float-right btn btn-primary"> {%trans "Browse it" %}</a>
{% endif %}
{% endblock %}

{% block content%}
<div class="col-12 col-lg-6 col-xl-4 mb-4">
    <div class="card">
        <div class="card-header">{%trans "Information"%}</div>
        <div class="card-body">
            <dl>
                <dt>{{object|field_verbose_name:"name"}}</dt>
                <dd>{{object.name}}</dd>
                <dt>{{object|field_verbose_name:"life_domain"}}</dt>
                <dd>{{object.life_domain}}</dd>
                {% if object.publication_url %}
                <dt>{{object|field_verbose_name:"publication_url"}}</dt>
                <dd><a href="{{object.publication_url}}" target="_blank"><i class="fa fa-file"></i> {%trans "Open it"%}</a></dd>
                {% elif object.owner == request.user %}
                <dt>{{object|field_verbose_name:"publication_url"}}</dt>
                <dd><i>{% trans 'None' %}</i> <i class="fa fa-eye-slash" title="{%trans 'Display only to the owner'%}"></i></dd>
                {% endif %}
                {%if object.description|length != 0 %}
                <dt>{{object|field_verbose_name:"description"}}</dt>
                <dd>{{object.description|linebreaksbr}}</dd>
                {%else%}
                {% if object.owner == request.user %}
                <dt>{{object|field_verbose_name:"description"}}</dt>
                <dd class="{%if object.public %}text-danger{%endif%}">
                    <i class="fa fa-exclamation-triangle {%if not object.public %}text-warning{%endif%}"></i>
                    {%trans "empty_description_is_bad"%}
                </dd>
                {%endif%}
                {%endif%}
                {%if object.public %}
                    <dt>{%trans "Visibility"%}</dt>
                    <dd>{%trans "Public"%}</dd>
                {%else%}
                    <dt>{%trans "Visibility"%}</dt>
                    <dd> {%trans "Private"%}
                        {% if request.user != object.owner %}
                            {% if request.user.is_staff or request.user.is_superuser %}
                                {%if not request|can_see:object%}
                                    {%trans "(Only visible as you are an admin)"%}
                                {%else%}
                                    {%trans "(The owner has allowed you to see it.)"%}
                                {%endif%}
                            {%else%}
                                {%trans "(The owner has allowed you to see it.)"%}
                            {%endif%}
                        {%endif%}
                    </dd>
                {%endif%}
                {% if request.user != object.owner %}
                    <dt>{%trans "Owner"%}</dt>
                    <dd>
                        <span class="text-uppercase">{{object.owner.last_name}}</span> {{object.owner.first_name}}
                        <a href="{% url 'viralhostrangedb:data-source-contact' pk=object.pk%}"
                           class="float-right"
                        >
                            <i class="fa fa-envelope"></i> {%trans "Contact owner"%}
                        </a>
                    </dd>
                {%endif%}
                {%if object.owner == request.user %}
                {%if not object.public %}
                <dt>
                    {{object|field_verbose_name:"allowed_users"}}
                    <i class="fa fa-eye-slash" title="{%trans 'Display only to the owner'%}"></i>
                </dt>
                <dd>
                    {%for user in object.allowed_users.all%}
                    <span class="text-uppercase">{{user.last_name}}</span> {{user.first_name}}{% if not forloop.last%},{%endif%}
                    {% empty %}
                    <i>{% trans 'None' %}</i>
                    {%endfor%}
                </dd>
                {%endif%}
                <dt>
                    {%trans "Origin"%}
                    <i class="fa fa-eye-slash" title="{%trans 'Display only to the owner'%}"></i>
                </dt>
                <dd>{{object.raw_name}} ({{object.get_kind_display}})</dd>
                {%endif%}
                <dt>{{object|field_verbose_name:"creation_date"}}</dt>
                <dd>{{object.creation_date}}</dd>
                <dt>{{object|field_verbose_name:"last_edition_date"}}</dt>
                <dd>{{object.last_edition_date}}</dd>
            </dl>
            {% if request|can_edit:object %}
            <a href="{% url 'viralhostrangedb:data-source-update' pk=object.pk%}" role="button"
               class="btn btn-outline-primary"><i class="fa fa-pencil"></i> {%trans "Update" %}</a>
            <a href="{% url 'viralhostrangedb:data-source-delete' pk=object.pk%}" role="button"
               class="float-right btn btn-outline-danger"><i class="fa fa-trash"></i> {%trans "Delete" %}</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="col-12 col-lg-6 col-xl-{% if has_responses %}4{%else%}8{%endif%} mb-4">
    <div class="card">
        <div class="card-header">{%trans "Content"%}</div>
        <div class="card-body">
            <table class="table">
                <tbody>
                <tr>
                    <th>{%trans "Viruses"%}</th>
                    <td>{{object.virus_set.count}}</td>
                </tr>
                <tr>
                    <th>{%trans "Hosts"%}</th>
                    <td>{{object.host_set.count}}</td>
                </tr>
                <tr>
                    <th>{%trans "Responses"%}</th>
                    <td>{{object.responseindatasource.count}}</td>
                </tr>
                </tbody>
            </table>
            <div class="btn-group  d-flex" role="group" aria-label="Get content">
                <a href="{% url 'viralhostrangedb:data-source-data-update' pk=object.pk%}" role="button"
                   class="btn btn-outline-primary"><i class="fa fa-upload"></i> {%trans "Update content" %}</a>
                {% if has_responses %}
                <a href="{% url 'viralhostrangedb:data-source-download' pk=object.pk%}" role="button"
                   class="float-right btn btn-outline-primary">
                    <i class="fa fa-download"></i> {%trans "Download it" %}
                </a>
                <a href="http://hub.pages.pasteur.fr/12765-viralhostrangedb/compatible_file.html" target="_blank" style="flex-grow:0"
                   class="float-right btn btn-outline-primary">
                    <i class="fa fa-question-circle"></i>
                </a>
                {%else%}
                <a href="{% url 'viralhostrangedb:data-source-download' pk=object.pk%}" role="button"
                   class="float-right btn btn-primary">
                    <i class="fa fa-download"></i> {%trans "Download template and fill it" %}
                </a>
                <a href="#example_table" role="button" style="flex-grow:0" data-toggle="collapse"
                   class="float-right btn btn-outline-primary">
                    <i class="fa fa-question-circle"></i> {%trans "How to fill it" %}
                </a>
                {%endif%}
            </div>

        </div>
        {% if example_table %}
        <div class="card-footer collapse" id="example_table">
            {{example_table}}
        </div>
        {% endif %}
    </div>
</div>
{% if has_responses%}
<div class="col-12 col-xl-4 mb-4">
    <div class="card">
        <div class="card-header">{%trans "Mapping used"%}</div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>{%trans "Response in data source"%}</th>
                    <th>{%trans "Response mapped"%}</th>
                </tr>
                </thead>
                <tbody>
                {%for raw,mapped in object.get_ordered_mapping%}
                <tr>
                    <td>{{raw}}</td>
                    <td><i class="fa fa-stop" style="color:{{mapped.color}}"></i> {{mapped.name}}</td>
                </tr>
                {%endfor%}
                </tbody>
            </table>
            {% if request|can_edit:object %}
            {% if object.is_mapping_done %}
            <a href="{%url 'viralhostrangedb:data-source-mapping-edit' pk=object.pk %}" role="button"
               class="float-right btn btn-outline-primary"><i class="fa fa-map-signs"></i> {%trans 'Edit mapping' %}</a>
            {%else%}
            <a href="{%url 'viralhostrangedb:data-source-mapping-edit' pk=object.pk %}" role="button"
               class="float-right btn btn-warning"><i class="fa fa-map-signs"></i> {%trans 'Complete mapping' %}</a>
            {%endif%}
            {%endif%}
        </div>
    </div>
</div>
{%endif%}
<div class="col-12 col-lg col-xl-6 mb-4">
    <div class="card">
        <div class="card-header">
            {%trans "Viruses"%}
            {% if request|can_edit:object %}
            <a class="btn btn-xs btn-outline-secondary pull-right"
               href="{% url 'viralhostrangedb:data-source-virus-delete' pk=object.pk%}"
               role="button"
               title="{%trans 'Delete some viruses' %}"
            >
                <i class="fa fa-trash"></i> {%trans "Delete ..." %}
            </a>
            <a class="btn btn-xs btn-outline-secondary pull-right"
               href="{% url 'viralhostrangedb:data-source-virus-update' pk=object.pk%}"
               role="button"
               title="{%trans 'Edit some viruses' %}"
            >
                <i class="fa fa-pencil"></i> {%trans "Edit ..." %}
            </a>
            {%endif%}
        </div>
        <div class="card-body">
            {%for o in object.virus_set.all %}<a target="_blank" href="{% url 'viralhostrangedb:virus-detail' pk=o.pk%}">
                {{o.explicit_name_html}}</a>{% if not forloop.last %}{%trans ","%}{%endif%}
            {%endfor%}
        </div>
    </div>
</div>
<div class="col-12 col-lg col-xl-6 mb-4">
    <div class="card">
        <div class="card-header">
            {%trans "Hosts"%}
            {% if request|can_edit:object %}
            <a class="btn btn-xs btn-outline-secondary pull-right"
               href="{% url 'viralhostrangedb:data-source-host-delete' pk=object.pk%}"
               role="button"
               title="{%trans 'Delete some hosts' %}"
            >
                <i class="fa fa-trash"></i> {%trans "Delete ..." %}
            </a>
            <a class="btn btn-xs btn-outline-secondary pull-right"
               href="{% url 'viralhostrangedb:data-source-host-update' pk=object.pk%}"
               role="button"
               title="{%trans 'Edit some hosts' %}"
            >
                <i class="fa fa-pencil"></i> {%trans "Edit ..." %}
            </a>
            {%endif%}
        </div>
        <div class="card-body">
            {%for o in object.host_set.all %}<a target="_blank" href="{% url 'viralhostrangedb:host-detail' pk=o.pk%}">
                {{o.explicit_name_html}}</a>{% if not forloop.last %}{%trans ","%}{%endif%}
            {%endfor%}
        </div>
    </div>
</div>
{% endblock%}

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/login_menu.html
{% extends "basetheme_bootstrap/login_menu.html" %}
{% block login_menu_staff_dropdown_items %}
{{block.super}}
<a  class="dropdown-item" href="https://gitlab.pasteur.fr/hub/12765-viralhostrangedb" target="_blank"><i class="fa fa-bug"></i> Issue tracking</a>
{% endblock %}

src/viralhostrange/viralhostrangedb/templates/viralhostrangedb/upper_nav_bar.html
{% extends "basetheme_bootstrap/upper_nav_bar.example.html" %}